### PR TITLE
Update action.yml

### PR DESCRIPTION
**Pull request by rohan472000**

### CODE REVIEW

**Review by alissatroiano — COMMENTED** [review]
We don't have a `main` branch - ours is `master`,  but we can change the name of the master branch to main

**Comment by rohan472000** [comment]
keep it master, don't change it to main.


but i can see that i have pushed to master branch only....where is main branch in that?????

**Review by alissatroiano — COMMENTED** [review]
what exactly does this action do?

**Comment by alissatroiano** [comment]
Can we close this one? I merged the other YAML file...

**Comment by rohan472000** [comment]
i have resolved the conflicts, you can merge this.

**Review by alissatroiano — APPROVED** [review]

**Pull request merged**
